from typing import Dict, Any, Tuple

def generate_fallback_strategy(context: Dict[str, Any]) -> Tuple[str, str]:
    """
    Generates a deterministic fallback negotiation strategy and financial advice
    when the Gemini AI service is unavailable.
    """
    # Sort loans by priority score descending
    loans = sorted(context.get("loans", []), key=lambda x: x['priority_score'], reverse=True)
    
    strategy_markdown = (
        "# Step-by-Step Debt Negotiation Strategy (Fallback Mode)\n\n"
        "*Notice: This strategy was generated by the local fallback engine because the Gemini AI service is currently offline. "
        "All calculations and targets remain fully customized to your profile.*\n\n"
    )
    
    for idx, loan in enumerate(loans, 1):
        strategy_markdown += (
            f"## Step {idx}: Negotiate with {loan['lender_name']} ({loan['priority_level']} Priority)\n"
            f"- **Loan Type**: {loan['loan_type']}\n"
            f"- **Outstanding Balance**: ₹{loan['outstanding_amount']:.2f} (EMI: ₹{loan['emi']:.2f}/mo)\n"
            f"- **Target Settlement Offer**: ₹{loan['recommended_amount']:.2f} ({loan['recommended_settlement_pct']}% of balance)\n"
            f"- **Core Hardship Argument**: Cite '{loan['reason']}' as the justification for restructured payment terms.\n"
            f"- **Recommended Tactic**: Contact the hardship department. Emphasize that your monthly surplus of "
            f"₹{context['monthly_surplus']:.2f} limits your capacity to make full payments and explain that a lump-sum settlement "
            f"of ₹{loan['recommended_amount']:.2f} is the maximum feasible offer.\n\n"
        )

    advice_markdown = (
        "# Actionable Financial Advice (Fallback Mode)\n\n"
        "*Notice: This financial advice was generated by the local fallback engine.*\n\n"
        f"1. **Evaluate Monthly Surplus**: Your monthly surplus is currently **₹{context['monthly_surplus']:.2f}** "
        f"(Monthly Income: ₹{context['monthly_income']:.2f} vs. Monthly Expenses: ₹{context['monthly_expenses']:.2f}). "
        f"We recommend auditing non-essential expenses immediately to increase this cash surplus.\n"
        f"2. **Address High Priority Debts First**: Focus payment adjustments on accounts with higher priority scores "
        f"({', '.join(l['lender_name'] for l in loans[:2]) if loans else 'N/A'}) to mitigate delinquency escalation.\n"
        f"3. **Request Temporary Hardship Terms**: Contact creditors to ask for interest rate concessions or temporary payment "
        f"moratoriums while you arrange settlement funding.\n"
    )
    
    return strategy_markdown, advice_markdown


def generate_fallback_letter(context: Dict[str, Any], lender_name: str = None) -> str:
    """
    Generates a deterministic fallback debt settlement offer letter template
    when the Gemini AI service is unavailable.
    """
    target_loans = context.get("loans", [])
    if lender_name:
        target_loans = [l for l in target_loans if lender_name.lower() in l['lender_name'].lower()]
    
    if not target_loans:
        target_loans = context.get("loans", [])
        
    loan = target_loans[0] if target_loans else None
    lender = loan['lender_name'] if loan else "[Lender Name]"
    outstanding = loan['outstanding_amount'] if loan else 0.0
    settlement = loan['recommended_amount'] if loan else 0.0
    pct = loan['recommended_settlement_pct'] if loan else 0.0
    reason = loan['reason'] if loan else "Severe financial distress"
    
    return f"""# Debt Settlement Offer Letter (Fallback Mode)

*Notice: This letter draft was generated by the local fallback engine because the Gemini AI service is currently offline.*

Date: [Insert Date]

To:
Hardship / Settlements Department
{lender}
[Creditor Address]

RE: Settlement Offer for Account of {context['user_name']}
Account Number Reference: [Insert Account Number]

Dear Settlement Manager,

I am writing to request a restructuring of my outstanding debt with {lender}. My account currently shows an outstanding balance of ₹{outstanding:.2f}.

Due to severe financial hardship, I am no longer able to meet my regular monthly payment obligations. My current monthly surplus is only ₹{context['monthly_surplus']:.2f} relative to my essential monthly expenses of ₹{context['monthly_expenses']:.2f}, causing severe financial stress ({context['stress_level']} level).

I propose a lump-sum payment of **₹{settlement:.2f}** as a full and final settlement of my debt. This amount represents **{pct}%** of the outstanding balance.

If you accept this settlement offer, please send a written agreement confirming that upon receipt of the settlement payment, my account will be closed and reported to credit bureaus as "settled in full" with a zero balance.

Thank you for your consideration in resolving this matter.

Sincerely,

___________________________
{context['user_name']}
Email: {context['user_email']}
"""
