import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  LayoutDashboard, 
  Coins, 
  UserCog, 
  HeartPulse, 
  Scale, 
  BrainCircuit, 
  FileSignature, 
  History, 
  LogOut, 
  Menu, 
  X,
  User,
  Bell,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Shield,
  Settings,
  AlertTriangle
} from 'lucide-react';
import authService from '../services/authService';
import profileService from '../services/profileService';
import { useToast } from '../hooks/useToast';

const Layout = ({ children }) => {
  const navigate = useNavigate();
  const location = useLocation();
  const { showToast } = useToast();
  
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [notifDropdownOpen, setNotifDropdownOpen] = useState(false);
  const [profileDropdownOpen, setProfileDropdownOpen] = useState(false);
  const [userName, setUserName] = useState('User');
  const [profileImage, setProfileImage] = useState(null);

  // Search feature states
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [searchFocused, setSearchFocused] = useState(false);

  const notifRef = useRef(null);
  const profileRef = useRef(null);
  const searchDropdownRef = useRef(null);

  const searchableResources = [
    { title: "Debt Overview & KPI Cards", page: "Dashboard", path: "/dashboard", desc: "View total outstanding debt, monthly DTI metrics, savings, and default risks." },
    { title: "Debt Default Analysis", page: "Dashboard", path: "/dashboard", desc: "Analyze debt stress margins, risk indicators, and cash flow projections." },
    { title: "EMI Reminders", page: "Dashboard", path: "/dashboard", desc: "View upcoming loan payment schedules, interest dues, and auto reminders." },
    { title: "Lender Accounts & Balance List", page: "Loans", path: "/loans", desc: "Manage credit cards, auto loans, personal loans, mortgages, and balances." },
    { title: "Add/Edit Loans", page: "Loans", path: "/loans", desc: "Register outstanding debts, specify interest rates, and adjust monthly EMIs." },
    { title: "Monthly Earnings & Expenses", page: "Financial Profile", path: "/profile", desc: "Define salary, business earnings, rent, household costs, and utilities." },
    { title: "Cash Flow Surplus", page: "Financial Profile", path: "/profile", desc: "Examine monthly surplus allocations and debt repayment capacity." },
    { title: "Credit Health Index", page: "Financial Health", path: "/health", desc: "Check DTI ratio, EMI burden score, and surplus safety threshold gauge." },
    { title: "ScoreDial SVG Health Ring", page: "Financial Health", path: "/health", desc: "Visual circular gauge displaying debt stress risk index score." },
    { title: "Settlement Target Recommendations", page: "Settlement", path: "/settlement", desc: "Compute payoff priorities, optimal settlement offers, and discount savings." },
    { title: "Lender Prioritization Indexes", page: "Settlement", path: "/settlement", desc: "Sort delinquent credit accounts by interest rate stress and default timeline." },
    { title: "Gemini AI Negotiation Chatbot", page: "AI Negotiation", path: "/negotiation", desc: "Interact with Gemini AI tactical agents to draft customized hardship statements." },
    { title: "Creditor Dialogue Scripts", page: "AI Negotiation", path: "/negotiation", desc: "Access bank settlement strategies and dialogue scripts for credit recovery." },
    { title: "AI Settlement Letters", page: "AI Letter", path: "/letter", desc: "Generate print-ready hardship settlement notice letters for bank creditors." },
    { title: "Print/Download Hardship Notices", page: "AI Letter", path: "/letter", desc: "Draft and export formal proposals, debt relief applications, and settlement contracts." },
    { title: "Interaction Logs & History", page: "AI History", path: "/ai-history", desc: "Review historical letters and negotiation strategies generated by Google Gemini." },
    { title: "My Profile Details", page: "My Profile", path: "/my-profile", desc: "Edit personal name, email, country, occupation, and customize profile avatar." },
    { title: "Change Password Security", page: "My Profile", path: "/my-profile", desc: "Update security login credentials and verify user profile settings." }
  ];

  const handleSearchChange = (e) => {
    const query = e.target.value;
    setSearchQuery(query);
    if (!query.trim()) {
      setSearchResults([]);
      return;
    }
    const filtered = searchableResources.filter(item => 
      item.title.toLowerCase().includes(query.toLowerCase()) ||
      item.page.toLowerCase().includes(query.toLowerCase()) ||
      item.desc.toLowerCase().includes(query.toLowerCase())
    );
    setSearchResults(filtered);
  };

  const notifications = [
    { id: 1, text: "High priority default risk alert on HDFC Loan", time: "5 mins ago", unread: true },
    { id: 2, text: "Gemini drafted negotiation strategy ready", time: "1 hour ago", unread: true },
    { id: 3, text: "Monthly cash surplus projection updated", time: "1 day ago", unread: false }
  ];

  useEffect(() => {
    profileService.getUserProfile()
      .then((res) => {
        if (res.success && res.data) {
          if (res.data.name) setUserName(res.data.name);
          if (res.data.profile_image) setProfileImage(res.data.profile_image);
        }
      })
      .catch(() => {});
  }, [location.pathname]);

  // Click outside listener to close dropdowns
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (notifRef.current && !notifRef.current.contains(event.target)) {
        setNotifDropdownOpen(false);
      }
      if (profileRef.current && !profileRef.current.contains(event.target)) {
        setProfileDropdownOpen(false);
      }
      if (searchDropdownRef.current && !searchDropdownRef.current.contains(event.target)) {
        setSearchFocused(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleLogout = () => {
    authService.logout();
    showToast('Logged out successfully.');
    navigate('/');
  };

  const navLinks = [
    { name: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { name: 'Loans', path: '/loans', icon: Coins },
    { name: 'Financial Profile', path: '/profile', icon: UserCog },
    { name: 'Financial Health', path: '/health', icon: HeartPulse },
    { name: 'Settlement', path: '/settlement', icon: Scale },
    { name: 'AI Negotiation', path: '/negotiation', icon: BrainCircuit },
    { name: 'AI Letter', path: '/letter', icon: FileSignature },
    { name: 'AI History', path: '/ai-history', icon: History }
  ];

  const getPageTitle = () => {
    const current = navLinks.find(link => link.path === location.pathname);
    if (current) return current.name;
    if (location.pathname === '/my-profile') return 'My Profile';
    return 'FinRelief AI';
  };

  const unreadCount = notifications.filter(n => n.unread).length;

  return (
    <div className="flex h-screen bg-[#0F1115] text-slate-100 overflow-hidden font-sans select-none">
      
      {/* 1. Desktop Sidebar */}
      <aside className={`hidden md:flex md:flex-col bg-[#1A1D24] border-r border-brand-border shrink-0 transition-all duration-300 ${
        sidebarCollapsed ? 'w-20' : 'w-64'
      }`}>
        {/* Header Logo */}
        <div className="p-6 border-b border-white/[0.04] flex items-center justify-between">
          <div className="flex items-center gap-3 overflow-hidden">
            <BrainCircuit className="w-8 h-8 text-brand-accent shrink-0 animate-pulse" />
            {!sidebarCollapsed && (
              <span className="font-display font-extrabold text-lg tracking-tight text-white animate-fade-in truncate">
                FinRelief AI
              </span>
            )}
          </div>
          {!sidebarCollapsed && (
            <button 
              onClick={() => setSidebarCollapsed(true)}
              className="p-1 rounded-lg text-slate-500 hover:text-white hover:bg-white/[0.04] transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
          )}
        </div>
        
        {/* Navigation list */}
        <nav className="flex-1 px-3 py-6 space-y-1 overflow-y-auto">
          {navLinks.map((link) => {
            const Icon = link.icon;
            const isActive = location.pathname === link.path;
            return (
              <Link
                key={link.path}
                to={link.path}
                className={`flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-medium transition-all duration-200 relative group ${
                  isActive 
                    ? 'bg-gradient-to-r from-brand-accent to-brand-accentLight text-black font-semibold shadow-lg shadow-brand-accent/20' 
                    : 'text-slate-400 hover:bg-white/[0.03] hover:text-white'
                }`}
              >
                <Icon className="w-5 h-5 shrink-0" />
                {!sidebarCollapsed && <span className="animate-fade-in">{link.name}</span>}
                
                {/* Collapsed Tooltip helper */}
                {sidebarCollapsed && (
                  <div className="absolute left-20 bg-brand-card border border-white/[0.06] p-2 rounded-lg text-xs font-semibold text-white scale-0 group-hover:scale-100 origin-left transition-all duration-200 shadow-xl z-50">
                    {link.name}
                  </div>
                )}
              </Link>
            );
          })}
        </nav>

        {/* Sidebar Footer details */}
        <div className="p-4 border-t border-white/[0.04] space-y-3">
          <Link 
            to="/my-profile"
            className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-white/[0.03] transition-all duration-200 cursor-pointer group"
          >
            {profileImage ? (
              <img 
                src={profileImage} 
                alt="Avatar" 
                className="w-9 h-9 rounded-full object-cover border border-brand-accent/20 shrink-0" 
              />
            ) : (
              <div className="w-9 h-9 rounded-full bg-brand-accent/10 flex items-center justify-center border border-brand-accent/20 text-brand-accent group-hover:bg-brand-accent group-hover:text-black transition-colors duration-200 shrink-0">
                <User className="w-4 h-4" />
              </div>
            )}
            {!sidebarCollapsed && (
              <div className="truncate">
                <p className="text-sm font-semibold text-slate-200 group-hover:text-white transition-colors truncate">{userName}</p>
                <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider block mt-0.5">Account Profile</span>
              </div>
            )}
          </Link>
          <button
            onClick={handleLogout}
            className="flex items-center gap-3 w-full px-4 py-3 rounded-xl text-sm font-semibold text-red-400 hover:bg-red-950/20 hover:text-red-300 transition-all duration-200"
          >
            <LogOut className="w-5 h-5 shrink-0" />
            {!sidebarCollapsed && <span>Logout</span>}
          </button>
        </div>
      </aside>

      {/* 2. Mobile Drawer Menu */}
      {mobileMenuOpen && (
        <div 
          className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm md:hidden"
          onClick={() => setMobileMenuOpen(false)}
        />
      )}
      <aside className={`fixed inset-y-0 left-0 z-50 flex flex-col w-64 bg-[#1A1D24] border-r border-brand-border transform transition-transform duration-300 ease-in-out md:hidden ${
        mobileMenuOpen ? 'translate-x-0' : '-translate-x-full'
      }`}>
        <div className="p-6 border-b border-white/[0.04] flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <BrainCircuit className="w-8 h-8 text-brand-accent" />
            <span className="font-display font-bold text-lg text-white">FinRelief AI</span>
          </div>
          <button 
            onClick={() => setMobileMenuOpen(false)}
            className="p-1 rounded-lg text-slate-400 hover:bg-white/[0.04] hover:text-white"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        <nav className="flex-1 px-4 py-6 space-y-1.5 overflow-y-auto" onClick={() => setMobileMenuOpen(false)}>
          {navLinks.map((link) => {
            const Icon = link.icon;
            const isActive = location.pathname === link.path;
            return (
              <Link
                key={link.path}
                to={link.path}
                className={`flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-medium transition-all duration-200 ${
                  isActive 
                    ? 'bg-gradient-to-r from-brand-accent to-brand-accentLight text-black font-semibold shadow-lg shadow-brand-accent/20' 
                    : 'text-slate-400 hover:bg-white/[0.04] hover:text-white'
                }`}
              >
                <Icon className="w-5 h-5 shrink-0" />
                <span>{link.name}</span>
              </Link>
            );
          })}
        </nav>
        <div className="p-4 border-t border-white/[0.04] space-y-3">
          <Link 
            to="/my-profile"
            onClick={() => setMobileMenuOpen(false)}
            className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-white/[0.03] transition-colors"
          >
            {profileImage ? (
              <img src={profileImage} alt="Avatar" className="w-9 h-9 rounded-full object-cover" />
            ) : (
              <div className="w-9 h-9 rounded-full bg-brand-accent/10 flex items-center justify-center text-brand-accent border border-brand-accent/20">
                <User className="w-4 h-4" />
              </div>
            )}
            <div>
              <p className="text-sm font-semibold text-slate-200">{userName}</p>
              <span className="text-[10px] text-slate-500 font-bold block mt-0.5">Account Profile</span>
            </div>
          </Link>
          <button
            onClick={handleLogout}
            className="flex items-center gap-3 w-full px-4 py-3 rounded-xl text-sm font-semibold text-red-400 hover:bg-red-950/20 hover:text-red-300 transition-colors"
          >
            <LogOut className="w-5 h-5 shrink-0" />
            <span>Logout</span>
          </button>
        </div>
      </aside>

      {/* 3. Main Viewport Area */}
      <div className="flex-1 flex flex-col overflow-hidden">
        
        {/* Top Navbar Header */}
        <header className="h-16 flex items-center justify-between px-6 bg-[#1A1D24] border-b border-brand-border z-30 shrink-0 relative">
          <div className="flex items-center gap-4">
            <button
              onClick={() => setMobileMenuOpen(true)}
              className="p-1.5 rounded-lg text-slate-400 hover:bg-white/[0.04] hover:text-white md:hidden"
            >
              <Menu className="w-5 h-5" />
            </button>
            
            <button
              onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
              className="hidden md:flex p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/[0.04] transition-colors"
            >
              {sidebarCollapsed ? <ChevronRight className="w-5 h-5" /> : <ChevronLeft className="w-5 h-5" />}
            </button>

            <h1 className="font-display font-extrabold text-lg text-white tracking-tight leading-none md:text-xl">
              {getPageTitle()}
            </h1>
          </div>

          {/* Search bar & Dropdowns */}
          <div className="flex items-center gap-4">
            
            {/* Search Bar widget (Fully Functional) */}
            <div className="relative" ref={searchDropdownRef}>
              <div className="hidden sm:flex items-center gap-2.5 bg-[#0F1115]/40 border border-brand-border rounded-xl px-3 py-1.5 w-60">
                <Search className="w-4 h-4 text-slate-500" />
                <input 
                  type="text" 
                  value={searchQuery}
                  onChange={handleSearchChange}
                  onFocus={() => setSearchFocused(true)}
                  placeholder="Search resources..." 
                  className="bg-transparent border-none text-xs text-slate-200 placeholder-slate-600 focus:outline-none w-full"
                />
              </div>

              {searchFocused && searchQuery.trim() !== '' && (
                <div className="absolute right-0 mt-3 w-80 bg-brand-card border border-brand-border rounded-2xl shadow-2xl p-4 z-50 animate-scale-up space-y-2">
                  <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest pb-1 border-b border-white/[0.04] mb-1">
                    Search Results
                  </div>
                  <div className="space-y-1.5 max-h-60 overflow-y-auto">
                    {searchResults.length > 0 ? (
                      searchResults.map((res, idx) => (
                        <Link
                          key={idx}
                          to={res.path}
                          onClick={() => {
                            setSearchQuery('');
                            setSearchResults([]);
                            setSearchFocused(false);
                          }}
                          className="block p-2 rounded-xl hover:bg-white/[0.02] text-xs transition-colors border border-transparent hover:border-brand-accent/10"
                        >
                          <div className="flex justify-between items-center mb-0.5">
                            <span className="font-semibold text-white truncate">{res.title}</span>
                            <span className="text-[8px] px-1.5 py-0.5 rounded bg-brand-accent/15 text-brand-accent font-bold uppercase shrink-0">{res.page}</span>
                          </div>
                          <p className="text-[10px] text-slate-400 leading-normal truncate">{res.desc}</p>
                        </Link>
                      ))
                    ) : (
                      <div className="text-center py-6 space-y-2">
                        <AlertTriangle className="w-6 h-6 text-brand-accent mx-auto animate-bounce" />
                        <h4 className="text-xs font-bold text-slate-200">No Results Found</h4>
                        <p className="text-[9px] text-slate-500 max-w-[200px] mx-auto leading-relaxed">
                          We couldn't find any resources matching "{searchQuery}".
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>

            {/* Notification Bell Dropdown */}
            <div className="relative" ref={notifRef}>
              <button 
                onClick={() => setNotifDropdownOpen(!notifDropdownOpen)}
                className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/[0.04] transition-colors relative"
              >
                <Bell className="w-4.5 h-4.5" />
                {unreadCount > 0 && (
                  <span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-brand-accent animate-ping" />
                )}
              </button>
              
              {notifDropdownOpen && (
                <div className="absolute right-0 mt-3 w-80 bg-brand-card border border-brand-border rounded-2xl shadow-2xl p-4 space-y-3 z-50 animate-scale-up">
                  <div className="flex justify-between items-center pb-2 border-b border-white/[0.04]">
                    <span className="text-xs font-bold text-slate-300">Notifications</span>
                    <span className="text-[10px] text-brand-accent font-semibold">{unreadCount} Unread</span>
                  </div>
                  <div className="space-y-2.5 max-h-60 overflow-y-auto">
                    {notifications.map(n => (
                      <div key={n.id} className="p-2.5 rounded-xl hover:bg-white/[0.02] text-xs transition-colors cursor-pointer space-y-1">
                        <p className={`leading-relaxed ${n.unread ? 'text-white font-semibold' : 'text-slate-400'}`}>{n.text}</p>
                        <span className="text-[9px] text-slate-500 block">{n.time}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* User Dropdown */}
            <div className="relative border-l border-white/[0.04] pl-4" ref={profileRef}>
              <button 
                onClick={() => setProfileDropdownOpen(!profileDropdownOpen)}
                className="flex items-center gap-2 group cursor-pointer focus:outline-none"
              >
                {profileImage ? (
                  <img src={profileImage} alt="Avatar" className="w-8 h-8 rounded-full object-cover border border-white/[0.04]" />
                ) : (
                  <div className="w-8 h-8 rounded-full bg-brand-accent/10 flex items-center justify-center text-brand-accent border border-brand-accent/20">
                    <User className="w-4 h-4" />
                  </div>
                )}
                <ChevronDown className="w-3.5 h-3.5 text-slate-500 group-hover:text-slate-300 transition-colors" />
              </button>

              {profileDropdownOpen && (
                <div className="absolute right-0 mt-3 w-48 bg-brand-card border border-brand-border rounded-2xl shadow-2xl py-2 z-50 animate-scale-up">
                  <div className="px-4 py-2 border-b border-white/[0.04] mb-1">
                    <p className="text-xs font-bold text-white truncate">{userName}</p>
                    <span className="text-[9px] text-slate-500 block">SaaS Client</span>
                  </div>
                  <Link 
                    to="/my-profile" 
                    onClick={() => setProfileDropdownOpen(false)}
                    className="flex items-center gap-2 px-4 py-2.5 text-xs text-slate-300 hover:bg-white/[0.03] hover:text-white transition-colors"
                  >
                    <Settings className="w-4 h-4 text-slate-500" /> Account Settings
                  </Link>
                  <Link 
                    to="/profile" 
                    onClick={() => setProfileDropdownOpen(false)}
                    className="flex items-center gap-2 px-4 py-2.5 text-xs text-slate-300 hover:bg-white/[0.03] hover:text-white transition-colors"
                  >
                    <Shield className="w-4 h-4 text-slate-500" /> Financial Profile
                  </Link>
                  <button 
                    onClick={handleLogout}
                    className="flex items-center gap-2 w-full px-4 py-2.5 text-xs text-red-400 hover:bg-red-950/20 hover:text-red-300 text-left border-t border-white/[0.04] mt-1 transition-colors"
                  >
                    <LogOut className="w-4 h-4 shrink-0" /> Logout
                  </button>
                </div>
              )}
            </div>

          </div>
        </header>

        {/* Scrollable Workspace Container */}
        <main className="flex-1 p-6 overflow-y-auto bg-[#0F1115] scrollbar-thin">
          <motion.div 
            key={location.pathname}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
            className="max-w-7xl mx-auto space-y-6"
          >
            {children}
          </motion.div>
        </main>
      </div>

    </div>
  );
};

export default Layout;
